version: '3.9'

services:
  app:
    build: .
    image: cliente-pet
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/clientpetdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=novaform1
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_DB: clientpetdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: novaform1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
